version: "3.9"

services:

  minio:
    image: minio/minio:latest
    environment:
      MINIO__ROOT_USER: minioadmin
      MINIO__ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - "9002:9000"
      - "9003:9001"
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 10s
      retries: 5
    restart: always

  minio-init:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 minioadmin minioadmin;
      mc mb local/aviation-lake --ignore-existing;
      mc mb local/mlflow --ignore-existing;
      echo 'Buckets created';
      exit 0;
      "
    restart: on-failure

  airflow:
    image: apache/airflow:2.8.1

    container_name: airflow

    depends_on:
      - minio

    ports:
      - "8080:8080"

    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src

    command: standalone

  ingestion:
    build: 
      context: .
      dockerfile: Dockerfile
    
    container_name: ingestion

    depends_on:
      minio:
        condition: service_healthy

    environment:
      MINIO__ENDPOINT: http://minio:9000
      MINIO__ACCESS_KEY: minioadmin
      MINIO__SECRET_KEY: minioadmin
      MINIO__BUCKET: aviation-lake

    volumes:
      - ./src:/app/src

    restart: on-failure

    




volumes:
  minio-data: